# Generated by Django 5.1.3 on 2024-11-21 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('age', models.PositiveIntegerField(default=1)),
                ('hunger', models.PositiveIntegerField(default=40)),
                ('happiness', models.PositiveIntegerField(default=40)),
                ('is_playing', models.BooleanField(default=False)),
            ],
        ),
    ]
